import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("http://localhost:5173/")
    page.get_by_role("textbox", name="Username").click()
    page.get_by_role("textbox", name="Username").fill("testuser")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("Test@123")
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Login").click()
    page.get_by_role("button", name="All").click()
    page.get_by_role("button", name="📱 Phones").click()
    page.get_by_role("button", name="💻 Laptops").click()
    page.get_by_role("button", name="📲 Tablets").click()
    page.get_by_role("button", name="Add to Cart").first.click()
    page.get_by_role("button", name="💻 Laptops").click()
    page.get_by_role("button", name="Add to Cart").nth(1).click()
    page.get_by_role("button", name="📱 Phones").click()
    page.get_by_role("button", name="Add to Cart").nth(2).click()
    page.get_by_role("button", name="Checkout").click()
    page.get_by_role("textbox", name="Email for invoice").click()
    page.get_by_role("textbox", name="Email for invoice").fill("test@example.com")
    page.get_by_role("textbox", name="Name on Card").click()
    page.get_by_role("textbox", name="Name on Card").fill("Test User")
    page.get_by_role("textbox", name="Card Number").click()
    page.get_by_role("textbox", name="Card Number").fill("4111111111111111")
    page.get_by_role("textbox", name="MM/YY").click()
    page.get_by_role("textbox", name="MM/YY").fill("12/30")
    page.get_by_role("textbox", name="CVV").click()
    page.get_by_role("textbox", name="CVV").fill("123")
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Pay $").click()
